README.md

bubbles: update README

---

.gitignore

Ignore PyCharm IDE settings.

---

README.md
deploy/README.md

bubbles: fix Ceph project name across README files

---

frontend/src/app/pages/login-page/login-page.component.scss
frontend/src/styles.scss

UI: Use Ceph brand colors in login page

---

frontend/src/app/core/top-bar/top-bar.component.html

UI: Rephrase signed in user menu

---

frontend/src/app/core/top-bar/top-bar.component.ts

UI: Rephrase sign out question.

---

frontend/src/app/core/navigation-bar/navigation-bar-item/navigation-bar-item.component.spec.ts
frontend/src/app/pages/dashboard-page/dashboard-page.component.spec.ts
frontend/src/app/shared/services/notification.service.spec.ts

UI: Simplify unit tests

---

module.py

a new event loop is needed when launching uvicorn from within a mgr module:
```
2021-09-23T09:07:04.803-0600 7f003007c640 -1 log_channel(cluster) log [ERR] : Unhandled exception from module 'bubbles' while running on mgr.x: There is no current event loop in thread 'Dummy-2'.
2021-09-23T09:07:04.803-0600 7f003007c640 -1 bubbles.serve:
2021-09-23T09:07:04.803-0600 7f003007c640 -1 Traceback (most recent call last):
File "/home/ceph/src/pybind/mgr/bubbles/module.py", line 70, in serve
uvicorn.run(self.app, host="0.0.0.0", port=1337)  # type: ignore
File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 393, in run
server.run()
File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 49, in run
loop = asyncio.get_event_loop()
File …
```

bubbles: run uvicorn in new event loop

---

.gitignore
deploy/README.md
deploy/build-container.sh
deploy/container/Dockerfile
deploy/plan/bootstrap-cluster.sh

Adds a build script that will handle including bubbles into the
container image for us.

bubbles/deploy: include bubbles in container

---

backend/api/auth.py
backend/api/host.py
backend/models/host.py
frontend/src/app/pages/hosts-page/hosts-page.component.html
frontend/src/app/pages/hosts-page/hosts-page.component.ts
frontend/src/app/shared/pipes/ceph-short-version.pipe.spec.ts
frontend/src/app/shared/pipes/ceph-short-version.pipe.ts
frontend/src/app/shared/pipes/pipes.module.ts
frontend/src/app/shared/services/api/host.service.spec.ts
frontend/src/app/shared/services/api/host.service.ts
frontend/src/app/shared/services/api/user.service.spec.ts
module.py

backend/frontend: Fill hosts page with real data

---

frontend/src/app/shared/components/declarative-form/declarative-form.component.html
frontend/src/app/shared/models/declarative-form-config.type.ts

Add 'checked' property to allow to define which radio button is checked.

UI: Improve the declarative form

---

backend/api/users.py
frontend/src/app/pages/users-page/users-page.component.ts
frontend/src/app/shared/services/api/user.service.spec.ts
frontend/src/app/shared/services/api/users.service.ts
module.py

Use plural as suggested by best practices.

Backend/Frontend: Rename API endpoint

---

backend/api/auth.py
backend/api/cluster.py
backend/api/host.py
backend/api/services.py
backend/api/status.py
backend/api/storage.py
backend/api/users.py
backend/auth.py
backend/config.py
backend/controllers/rest_api_proxy.py
backend/models/service.py
backend/models/user.py
backend/tests/conftest.py
module.py

Signed-off-by: Michael Fritch <mfritch@suse.com>

bubbles: apply changes from python black

---

backend/models/service.py
frontend/src/app/pages/login-page/login-page.component.ts
frontend/src/app/shared/services/dialog.service.ts

backend/frontend: Misc improvements

---

requirements.txt

fixes various issues with asyncio event loops:
https://github.com/encode/uvicorn/releases/tag/0.15.0
Signed-off-by: Michael Fritch <mfritch@suse.com>

bubbles: update to uvicorn 0.15.0

---

frontend/src/app/functions.helper.spec.ts
frontend/src/app/pages/services-page/services-page.component.ts
frontend/src/app/shared/components/declarative-form/declarative-form.component.ts
frontend/src/app/shared/directives/dimless-binary.directive.ts
frontend/src/app/shared/models/declarative-form-config.type.ts

- Add callback to declarative form which is called on value changes
- Add 'Estimated Required Capacity' field to service creation page

frontend: Enhance services page

---

backend/api/services.py
backend/controllers/services.py
frontend/src/app/pages/services-page/services-page.component.ts
frontend/src/app/shared/components/declarative-form/declarative-form.component.html
frontend/src/app/shared/components/declarative-form/declarative-form.component.scss
frontend/src/app/shared/components/declarative-form/declarative-form.component.ts
frontend/src/app/shared/models/declarative-form-config.type.ts
frontend/src/app/shared/pipes/pipes.module.ts
frontend/src/app/shared/pipes/to-string.pipe.spec.ts
frontend/src/app/shared/pipes/to-string.pipe.ts
frontend/src/app/shared/services/api/services.service.spec.ts
frontend/src/app/shared/services/api/services.service.ts
frontend/src/app/shared/services/api/users.service.spec.ts
frontend/src/app/shared/services/api/users.service.ts

- Add hints to form fields
- Remove useless methods in UsersService
- Add ability to delete services

frontend: Enhance the services page

---

backend/api/services.py
backend/controllers/services.py
frontend/src/app/pages/services-page/services-page.component.ts
frontend/src/app/shared/components/declarative-form/declarative-form.component.ts
frontend/src/app/shared/models/declarative-form-config.type.ts
frontend/src/app/shared/services/api/services.service.spec.ts
frontend/src/app/shared/services/api/services.service.ts

- Rename wordings in service page
- Enhance services API

backend/frontend: Various improvements

---

frontend/src/app/pages/services-page/services-page.component.ts

- Disable 'Edit' menu for services
- Remove useless code
- Debounce service name exists requests

frontend: More services page improvements

---

frontend/src/app/core/dashboard/widgets/events-dashboard-widget/events-dashboard-widget.component.ts

frontend: Use pipe to render the date column

---

frontend/src/app/shared/components/declarative-form/declarative-form.component.ts

Apply modifier to form field on form initialization.

---

frontend/src/app/core/dashboard/widgets/health-dashboard-widget/health-dashboard-widget.component.html
frontend/src/app/core/dashboard/widgets/health-dashboard-widget/health-dashboard-widget.component.scss
frontend/src/app/shared/components/widget/widget.component.html
frontend/src/app/shared/components/widget/widget.component.scss
frontend/src/app/shared/components/widget/widget.component.ts
frontend/src/styles.scss

Frontend: Various improvements to the dashboard

---

frontend/src/app/core/layouts/main-layout/main-layout.component.scss

Frontend: Fix overflow issue in main layout

---

frontend/angular.json

frontend: crank up budgets significantly

---

deploy/run-registry.sh

To help running a local registry.

deploy: add 'run-registry' script

---

deploy/build-container.sh

deploy: fix build-container script

---

backend/api/ceph/fs.py
backend/api/ceph/nfs.py
backend/api/ceph/osd.py
backend/controllers/ceph/__init__.py
backend/controllers/ceph/ceph.py
backend/controllers/ceph/fs.py
backend/controllers/ceph/nfs.py
backend/controllers/ctrls.py
backend/controllers/services.py

move ceph related items (cephfs, nfs, etc.) into a dedicated
CephController
Signed-off-by: Michael Fritch <mfritch@suse.com>

bubbles: add a dedicated CephController

---

backend/api/ceph/fs.py
backend/api/ceph/nfs.py
backend/api/ceph/osd.py
backend/controllers/ceph/fs.py
backend/controllers/ceph/osd.py
backend/controllers/services.py
backend/models/ceph/nfs.py

address comments from #62
Signed-off-by: Michael Fritch <mfritch@suse.com>

bubbles: clean-up NFS filesystem service

---

frontend/src/app/shared/components/dialog/dialog.component.ts

Frontend: Fix button colors when type is 'warning' or 'danger'

---

frontend/src/app/core/dashboard/widgets/performance-bytes-dashboard-widget/performance-bytes-dashboard-widget.component.html
frontend/src/app/core/dashboard/widgets/performance-bytes-dashboard-widget/performance-bytes-dashboard-widget.component.ts
frontend/src/app/core/dashboard/widgets/performance-operations-dashboard-widget/performance-operations-dashboard-widget.component.html
frontend/src/app/core/dashboard/widgets/performance-operations-dashboard-widget/performance-operations-dashboard-widget.component.ts
frontend/src/app/core/dashboard/widgets/services-utilization-dashboard-widget/services-utilization-dashboard-widget.component.html
frontend/src/app/core/dashboard/widgets/services-utilization-dashboard-widget/services-utilization-dashboard-widget.component.ts
frontend/src/app/core/dashboard/widgets/storage-utilization-dashboard-widget/storage-utilization-dashboard-widget.component.html
frontend/src/app/core/dashboard/widgets/storage-utilization-dashboard-widget/storage-utilization-dashboard-widget.component.ts

Check https://github.com/xieziyu/ngx-echarts#directive for more information.

Frontend: Update the echart widgets the correct way

---

frontend/src/app/shared/components/datatable/datatable.component.spec.ts

Frontend: Fix unit test

---

frontend/src/app/pages/users-page/users-page.component.ts
frontend/src/app/shared/components/datatable/datatable.component.ts

Frontend: Remove useless prop and fix default value

---

frontend/src/app/shared/components/datatable/datatable.component.html
frontend/src/app/shared/models/datatable-action-item.type.ts

Frontend: Add ability to disable a menu item in a datatable action column

---

frontend/src/app/pages/hosts-page/hosts-page.component.html
frontend/src/app/pages/hosts-page/hosts-page.component.scss
frontend/src/app/pages/hosts-page/hosts-page.component.ts
frontend/src/app/pages/services-page/services-page.component.html
frontend/src/app/pages/services-page/services-page.component.scss
frontend/src/app/pages/services-page/services-page.component.ts
frontend/src/app/pages/users-page/users-page.component.html
frontend/src/app/pages/users-page/users-page.component.scss
frontend/src/app/pages/users-page/users-page.component.ts
frontend/src/app/shared/components/alert-panel/alert-panel.component.scss
frontend/src/app/shared/components/components.module.ts
frontend/src/app/shared/components/content-page/content-page.component.html
frontend/src/app/shared/components/content-page/content-page.component.scss
frontend/src/app/shared/components/content-page/content-page.component.spec.ts
frontend/src/app/shared/components/content-page/content-page.component.ts

This component is responsible for displaying the loading and error status of a page.
Additionally fixes a problem with the alignment of the alert box icon.

Frontend: Add content page component

---

deploy/README.md

Signed-off-by: Tatjana Dehler <tdehler@suse.com>

bubbles/deploy: fix minor issues in setup guide

---

frontend/jest.config.js
frontend/package.json

See https://thymikee.github.io/jest-preset-angular/docs/guides/angular-ivy/

Use JS based Jest configuration to be able to use 'ngcc-jest-processor'.

---

deploy/.gitignore

Ignore SSH keys generated while building a container

---

frontend/src/app/app-routing.module.ts

Display a notification if Dashboard is not reachable

---

frontend/src/app/pages/services-page/services-page.component.ts

Modifying the placeholder to make it easier to understand

---

backend/models/host.py
frontend/src/app/pages/hosts-page/hosts-page.component.ts
frontend/src/app/shared/services/api/host.service.ts

Adapt /api/host response model

---

frontend/src/app/shared/components/datatable/datatable.component.scss

Hide overlapping text in table cells

---

frontend/src/app/shared/components/datatable/datatable.component.spec.ts
frontend/src/app/shared/components/datatable/datatable.component.ts

Fixes: https://github.com/ceph/bubbles/pull/118

Fix unit tests
